### PR TITLE
added basic stacked bar plots

### LINKED ISSUE #6: Create function to generate stacked barplot for a single subquestion
image

image

### What
- A function that creates a horizontal bar plot containing either one (party-aggregated) or three (party-disaggregated) stacked bars, each displaying the percentages of respondents who endorsed each Likert outcome for that subquestion

### Function input(s)
- `question`
- `sub-question`
- optional `state`
- optional outcome threshold (e.g., 3+, 4+, none)
- boolean variable for whether user has selected to stratify by party
  - Note: when this is true, the state param state should always be none - i.e., party results will only ever be shown at whole sample (national) level

### Plot requirements
- [x] For a single stacked bar, each sub-bar corresponds to a Likert outcome for the given sub-question and should show the percentage endorsed (see `percentage` column in data tables)
  - The percentage endorsed will either represent the percentage for the whole sample or for a selected state
  - [x] If no outcome threshold specified:
    - should display all outcomes except for 3+/4+ aggregates (have their own entries in the data tables)
  - [x] If outcome threshold specified (3+ or 4+)
    - probably easiest for the stacked bar to become binarized, with one sub-bar showing the percentage for 3+ (i.e., those who endorsed level "3" or greater) and one bar with the percentage for all other levels (might need some math here)
    - Note: in the data tables, every sub-question has a 3+/4+ entry regardless of number of actual Likert levels for that question
      - however, if the subquestion is binarized (yes/no), probably the outcome threshold should have no effect
- [x] If stratify by party enabled, the plot will have one stacked bar per party
- Note: the number and meaning of Likert levels are expected to be the same for all sub-questions attached to a given question, but are not necessarily the same across questions - see the data dictionary

### Function output(s)
- [x] Plotly figure object
- The percentage endorsement associated with the 3+ Likert threshold
   - (This is for being able to later sort subquestions based on endorsement of 3+ responses)
   - If stratify by party is true, return the value for the party with the highest endorsement at that threshold

### Relevant data files
opinions_wholesample.tsv
opinions_state.tsv
opinions_party.tsv
subquestion_dictionary.tsv
outcome_dictionary.tsv

https://miro.com/app/board/uXjVKTjgU_s=/?share_link_id=830566650759

### PR DESCRIPTION
**Pull request by nikhil153**
- Closes #6 

Example of binarized stacked bar for 3+ threshold:
3+_stackedbar

Example of stacked bar showing all Likert levels:
all_levels_stackedbar

Example of binarized stacked bar, stratified by party:
party_3+_stackedbar

### CODE REVIEW

**Comment by michellewang** [comment]
Just a note here: there is survey data showing up in the notebook because its outputs haven't been cleared. We should probably clear the notebook and rewrite Git history (I think a `git commit --amend --no-edit` then `git push -f` should do it, but there might be other ways too)

**Comment by alyssadai** [comment]
Thanks a lot for catching that @michellewang! Just forced pushed to remove the notebook - let me know if things still don't look right.

**Comment by michellewang** [comment]
Looks good to me! Also realized that my screenshots in the other PRs also technically show data (in map colours/hoverboxes/bar plots) -- should I remove those as well or do you think it is less of an issue?

**Comment by alyssadai** [comment]
@michellewang I believe that’s fine for now, since that’s likely the desired behaviour for the plots in the app anyways !

**Comment by alyssadai** [comment]
Thanks @nikhil153 for your work on this 🎉. I pushed some minor clarity-related changes to the code and simplified the plot formatting a bit so it looks more like the Yale climate map bar plots.

The stacked bars are currently still missing full-text labels for the actual outcomes ("Moderately agree", "Agree", etc...), but because I think we need additional info about which ones to use when the bars are binarized, I've opened a separate [issue](https://github.com/neurodatascience/us_climate_emotions_map/issues/22) for that.

**Pull request merged**
