### PR TITLE
[ENH] Add script for making descriptive bar plots

### LINKED ISSUE #5: Create function to generate a sample description plot
### What
- A function that creates a histogram based on a given sample descriptive variable, for either the whole sample or a selected state
  - Can be multiple functions if different descriptive variables require slightly different plots
  - Likely easier than one single fixed subplot grid to reorder in the app if needed
- Alternative: A function that creates a plot containing a subplot per sample descriptive variable (https://plotly.com/python/subplots/) for either the whole sample or a state, since it will always be the same ones
  - May involve a utility function that handles the first anyways

### Function input(s)
- Optional state
- Demographic variable from `demographic_variable` column (for option 1)

### Full list of required histograms (all descriptive variables categorical):
- age
- employed (is respondent employed?)
- ethnicity
- hh_origin (household origin of respondent)
- location
- party
- race
- sex
- student (is respondent a student?)
- impact
  - ** there is actually yes/no data for 7 named weather impacts. these might make sense to combine into a single plot

### Plot requirements:
- Ideally, each histogram displays percentages (e.g., on hover or as another text label on each bar) alongside the N values per category

### Function output(s):
- Plotly figure object

### Relevant data files:
sampledesc_wholesample.tsv
sampledesc_state.tsv
impacts_list.tsv

### Notes:
Total N for either the state/whole sample will be handled + displayed separately outside of this plot/function

Example
image

### PR DESCRIPTION
**Pull request by michellewang**
Closes #5.

Feedback welcome, especially about the layout since I don't think it looks great at the moment and we will have to see how it integrates into the dashboard. Also this is using the default colours but we probably want to customize them

Example (whole sample):

Screenshot 2024-05-11 at 7 32 10 PM

### CODE REVIEW

**Review by alyssadai — COMMENTED** [review]
This is looking great, thanks @michellewang!

I left some suggestions to simplify the code a bit; feel free to take what makes sense to you.

In terms of layout, I'm sure Eric will have his own opinions (so we may want to wait to implement some of the following until Friday), but some ideas from me:
- Now that I'm looking at the bar plots, I'm wondering if it's more visually intuitive to have the y-axis be %, and show the actual counts on hover instead. Wdyt?
- If we *do* want to keep counts on the y-axis, might be worth having a y-axis title/titles that say "count (1000s)" or similar, and just make the axis tick labels integers, if that makes sense
- For the demographic variables w/ longer categories (political party, employment status, household origin), maybe we can wrap the x-axis tick labels so they don't extend as far. [Here's](https://github.com/neurobagel/digest/blob/1746a31ae7034808f4847233d791bb5f1bc94918/digest/plotting.py#L44-L55) a function I used to do this in the digest dashboard, for reference (there might be easier ways). If that seems like too much hassle however, we could just add more vertical space between plots so there's no overlap. totally up to you
- Since q2 is a bit unique but still has long category labels, maybe exceptionally for this plot, we could switch the orientation of x and y such that the likert responses are on the y, and the counts/proportions along the x. Perhaps that could help to a) distinguish it from the other demo variables 2) make it more readable (?)
- In general, I think a slightly bigger gap b/w subplots on the same row may be nice (the bars themselves can be fairly thin), for more visual whitespace?

If you strongly agree with any of the above, maybe you can implement them before merging. For the rest, we can revisit on Friday :)

Also, if you find any of the customization challenging using plotly graph_objects, I suggest checking out plotly express, which is more high-level but should have a simpler syntax (this is what I used for the dashboard)

**Review by alyssadai — APPROVED** [review]
(gonna approve this guy since it's functional !)

**Comment by alyssadai** [comment]
Hey @Remi-Gau, pinging you here in case you have more feedback on the sample descriptive plots :)

These will live in a drawer component that can be toggled visible or not in the app, see GIF preview in:
- https://github.com/neurodatascience/us_climate_emotions_map/pull/19

**Comment by michellewang** [comment]
Merging since I won't have time to change this before the meeting tomorrow

**Pull request merged**
